# Generated by Django 2.2.19 on 2022-03-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.PositiveSmallIntegerField(unique=True)),
                ('invite_code', models.CharField(max_length=6)),
                ('activated_code', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('confirmation_code', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
